services:
  # 1. Service Aplikasi (Laravel/PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_laravel_app
    restart: unless-stopped
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
      - redis

  # 2. Service Web Server (Nginx)
  nginx:
    image: nginx:alpine
    container_name: project_laravel_nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  # 3. Service Database (MySQL)
  db:
    image: mysql:8.0
    container_name: project_laraveldb_komputasi2
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  # 4. Service Cache (Redis)
  redis:
    image: redis:alpine
    container_name: project_laravel_redis
    restart: unless-stopped
    networks:
      - app-network

  # 5. Service Email Catcher (Mailpit)
  mailpit:
    image: axllent/mailpit
    container_name: project_laravel_komputasi
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    name: praktikum2cc
