version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_laravelcc2_tugas
    restart: unless-stopped
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: project_laravelcc2_nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: project_laravelcc2_mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    container_name: project_laravelcc2_redis
    restart: unless-stopped
    networks:
      - app-network

  mailpit:
    image: axllent/mailpit
    container_name: project_laravelcc2_mailpit
    restart: unless-stopped
    ports:
      - "1030:1025"
      - "8030:8025"
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: project_laravelcc2_jenkins
    restart: unless-stopped
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network   

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    name: praktikum2cc
  jenkins_home: {}   
